language: scala
scala:
- 2.12.3
script:
- sbt ciBuild
notifications:
  slack:
    secure: rleTyU5kFsOY3GWUiLnBN9bYxrLBTFtqeVGTgjkS7I+L+Dvb+2dbifNS9mlk5C0J7lbSMsypsqAUBfsvj/4inqLATAu+h0Wgzf0Y2IcYYSJ37yMHkYm7MTl/ivyhE7qWqC+CxZIQKACSiB/o70TwI2x6MxvxVwvw/DRzWdou8Oyg24440FJr3wiiebggJwvUSw6TaAnlQl+vi7jv8p40E+CJQFp11J4F5Dab8ExFPJoOFg4y3qca0tjwv6jwr40f3ppjX1VIMeqT10Zo62ni7QLx37ESiaFliV85yJ3Mehks9w5WmHGSHC4PLSILK5Wc+Mx6P0Qtv/1a/wmUUIBUItcyTqcMhvO3CW1if7wSzXH4gbuIhVp4eNQR3fqBvEdzijepkjS9w3FDNf1pwTtjcehD5KM9rqnWFw4WJgyVn2sH1t0bu/+vFB9/5D4f8OpSeoQYenxtzbLTPbKuhGyZI9/tqK+7A/X3Q4ssnDI4FXXBKLuUOikLH59qg6+X3F8KSFUSGFUiFiD51jKTDEKDUMb9M1MHurnY6W0+H8kX0Zcv05xrx/quviFgg9GkVz57D+o4zDpVrbWMTXBRdsXHjfYgXhqix6wtFgCvJxtH+UIdo0rmCG6acm8R++HqlAI8OdFfZJffuMgqIU5oLZbWu3WIa0VG0IjCFGT6nbjQIGc=
