name: Scala CI
permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up SBT
      uses: coursier/setup-action@v1.3.9
      with:
        jvm: temurin:21
        apps: sbt
    - name: Run tests
      run: sbt ciBuild
