name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Set up SBT
      uses: coursier/setup-action@v1
      with:
        jvm: temurin:21
        apps: sbt
    - name: Run tests
      run: sbt ciBuild
